### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by massimo-sala** [DarkWiiPlayer/lua-warn#1]
If LUA 5.4 warn doesn't support nginx logging, I ask you this change:
 - check nginx module
 - if it is loaded, replace builtin warn with your code

This way
 - LUA 5.4 can use nginx loggin
 - warnings under 5.3 and 5.4 have the same behaviour

M

**Comment by DarkWiiPlayer** [comment]
This could technically be done by just reassigning the global `warn` function to `require 'warn.compatible'`, but it might be neat to have some alternative way of doing this as well. Maybe `require 'warn' ()` to install the replacement unconditionally?

**Comment by DarkWiiPlayer** [comment]
The `nginx` override has now been moved into a different submodule that can load extensions.

It is likely that this will sooner or later move into its own project, as it really goes way beyond what `lua-warn` was originally meant to do (a simple compatibility layer for Lua < 5.4).

**Comment by DarkWiiPlayer** [comment]
This feature has now been completely moved into a [separate project](https://github.com/DarkWiiPlayer/lua-warn-ex) and is no longer part of `warn`
