### ISSUE TITLE
monkey-patch or not? pls explain

### ISSUE THREAD

**Issue by massimo-sala** [DarkWiiPlayer/lua-warn#2]
I read your message on LUA mailing list.
Quoting:

> It can both monkey-patch the warn function everywhere or just return its
> custom implementation, depending on whether environment pollution is
> acceptable.

What do you mean?
I don't see where your code checks "environment pollution is acceptable".

**Comment by DarkWiiPlayer** [comment]
If you just want the module to be available everywhere, you can just use `require 'warn'` and it will set the `warn` global to the new function if it's not already set.

When writing a library, this is usually unwanted, so you can limit the module to the current scope with `local warn = warn or require 'warn.compatible'`, without affecting other sections of the program that may or may not define their own `warn` function separately.
